name: CI
on:
  push:
    branches:
      - 'v5.3.*'
  pull_request:
    branches:
      - 'v5.3.*'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  ci:
    name: '${{ matrix.os.name}} | Java ${{ matrix.java.version}}'
    runs-on: ${{ matrix.os.id }}
    timeout-minutes: 60
    if: ${{ github.repository == 'Nordix/spring-framework' }}
    strategy:
      matrix:
        os:
          - id: ubuntu-latest
            name: Linux
        java:
          - version: 8
            toolchain: false
          - version: 11
            toolchain: true
          - version: 17
            toolchain: true

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
      - name: Build
        id: build
        uses: ./.github/actions/build
        with:
          java-version: ${{ matrix.java.version }}
          java-toolchain: ${{ matrix.java.toolchain }}
